### ISSUE TITLE
Unregister or Overriding ?

### ISSUE THREAD

**Issue by rafaelcorbellini-egsys** [jonsamwell/flutter_simple_dependency_injection#13]
Is there any attempt to unregister something registered? or some way to override something already registered (mapped).

example on Kiwi:
https://pub.dev/packages/kiwi#unregistering

**Comment by jonsamwell** [comment]
Hi @rafaelcorbellini-egsys, thanks for the suggestion.  I have added a way to remove a mapping or all mappings for a type.  This is available in version 1.0.3 https://pub.dev/packages/flutter_simple_dependency_injection/versions/1.0.3

``` 
  injector.removeMapping<SomeType>();

  injector.removeMapping<SomeType>(key: 'some_key');

  injector.removeAllMappings<SomeType>();
```
