### ISSUE TITLE
Renamings (suggestion for better names)

### ISSUE THREAD

**Issue by ova2** [jonsamwell/flutter_simple_dependency_injection#16]
When my PR is accepted (https://github.com/jonsamwell/flutter_simple_dependency_injection/pull/15), I would like to discuss some renamings with you. I would like to suggest the following renamings in public API which fit better the dependency injection in my opinion:

`map<T>` -> `bind<T>`
`removeMapping<T>` -> `unbind<T>`
`removeAllMappings<T>` -> `unbindAll<T>`
`mapWithParams<T>` -> `bindWithParams<T>`
`additionalParameters` -> `params`
`key` -> `qualifier`

One note to the "key". In other DI frameworks (such as Spring DI container, etc.), they speak about "qualifier". You can define and inject different instances of the same type by using __qualifiers__. An example of `unbind` method with `qualifier`:

```
Injector unbind<T>({String qualifier}) {
  final objectKey = _makeKey(T, qualifier);
  if (_factories.containsKey(objectKey)) {
    _factories.remove(objectKey);
  }
  return this;
}
```

What do you think? If you agree, I will do all work (renamings + changes in README) and provide a PR. Thanks.

**Comment by ova2** [comment]
Another suggestion is to make the `Injector` singleton. No needs to write `Injector.getInjector()`. The singleton injector instance could be retrieved by simple `Injector()`. This is what I made in our fork on my job.

```dart
  factory Injector([String name = 'default']) {
    if (!_injectors.containsKey(name)) {
      _injectors[name] = Injector._internal(name);
    }

    return _injectors[name];
  }

  Injector._internal(this.name);
```

I use `factory`. @jonsamwell What do you think?

**Comment by jonsamwell** [comment]
I think the naming is a matter of perspective and choice.  From a Java world these new naming conventions make sense, from a .Net world not so much.  The problem being is that it would be a very large breaking change for people using this library and for most people it probably wouldn't be a simple find+replace all change.  Much to my dismay I think people don't really follow the injector module idea so they would have references to the injector and mapping scatter throughout their projects.

I am happy with the Injector function change though as long as we keep the `.getInjector' method but mark it as deprecated.

Thanks for your contribution here, it is very much appreciated.

**Comment by ova2** [comment]
Ok, no problem, you're right.

Module concept is fine, but I name them "DI containers" in my projects. Every DI container has two methods "bindDependencies" and "unbindDependencies". But this is matter of taste.

After the PR is merged, I will provide another one with Injector function change and mark the `.getInjector` deprecated.

Another idea: introduce annotation(s) and code generation by means of `build_runner`. We could annotate types on class and parameter level in order to be able to generate mapping code automatically.
