### ISSUE TITLE
[FEATURE] Null safety

### ISSUE THREAD

**Issue by EArminjon** [jonsamwell/flutter_simple_dependency_injection#18]
Is null safety planned to be supported :) ?

**Comment by jonsamwell** [comment]
It is indeed, I just have to get around to it, feel free to submit a PR

**Comment by rcorbellini** [comment]
> It is indeed, I just have to get around to it, feel free to submit a PR

@jonsamwell 
Check My PR, i already do support for Null-safety.

https://github.com/jonsamwell/flutter_simple_dependency_injection/pull/14

@EArminjon 
If you wanna try a developer preview (while PR is in analyse), you can use my forked version (its updated with upstream):
https://github.com/rcorbellini/flutter_simple_dependency_injection

**Comment by jonsamwell** [comment]
Done v2.0.0.0!
