### ISSUE TITLE
Question on registering generic class

### ISSUE THREAD

**Issue by sxtfv** [jonsamwell/flutter_simple_dependency_injection#20]
First of all, thank you for the great package, it helped me a lot. What I am trying to do is to register generic class and didn't find if that's possible with this package. Could you please advise?
I have the following class:
```
import 'dart:developer';

abstract class Logger<T> {
  void info(String message);
}

class MyLogger<T> implements Logger<T> {
  @override
  void info(String message) {
    log(message, name: T.toString());
  }
}
```
And trying to inject it the following way:
```
if (!injector.isMapped<Logger/*=S*/>()) {
    injector.map<Logger/*=S*/>(
        (i) => MyLogger/*=S*/(),
    );
}
```
Finally, I am trying to use this setup:
```
final logger = Injector().get<Logger<LoadingScreen>>();
logger.info('Message');
```
and see the following message in developer console:
```
I/flutter ( 9776): reporting fatal error: Injector Exception: Cannot find object factory for 'Logger<LoadingScreen>::default'
I/flutter ( 9776): #0      Injector.get (package:flutter_simple_dependency_injection/src/injector.dart:237:7)
I/flutter ( 9776): #1      _LoadingScreenState._initAppData (package:monitask/screens/loading.dart:48:26)
I/flutter ( 9776): <asynchronous suspension>
```
If I change my code to this: `Injector().get<Logger<dynamic>>()` it works but this is not how I wanted to use it, I want to use it like `get<Logger<ClassA>>()` `get<Logger<ClassB>>()` etc
I am a little bit new to dart and flutter and don't know if that possible at all. Any suggestions would be very appreciated
Thank you!

**Comment by jonsamwell** [comment]
Hi @sxtfv,

I am not familiar with the `injector.isMapped<Logger/*=S*/>()` syntax or was this just an example?

I think the problem you are encountering is that the actual concrete type whether that is Logger<ClassA> or Logger<ClassB> is not actually mapped.

When you do this:

```
if (!injector.isMapped<Logger/*=S*/>()) {
    injector.map<Logger/*=S*/>(
        (i) => MyLogger/*=S*/(),
    );
}
```

I think it might be overwriting the base type of Logger<> rather than adding a new type.

I think this would work 

```
if (!injector.isMapped<Logger/*=S*/>(key: Logger/*=S*.runtimeType.toString())) {
    injector.map<Logger/*=S*/>(
        (i) => MyLogger/*=S*/(),
       key: Logger/*=S*.runtimeType.toString()
    );
}

final logger = Injector().get<Logger<LoadingScreen>>(key: Logger<LoadingScreen>.runtimeType.toString());

// you might have to wrap this code in a generic function to the able to access the type

Logger<T> get<T>() {
if (!injector.isMapped<Logger<T>>(key: T.toString())) {
    injector.map<Logger<T>>(
        (i) => Logger<T>(),
       key: T*.runtimeType.toString()
    );
}

return injector.get<Logger<T>>(key: T.toString());
}
```

Code hasn't been tested

**Comment by sxtfv** [comment]
@jonsamwell 
Thank you for your reply.
Unfortunately, this 
```
if (!injector.isMapped<Logger/*=S*/>(key: Logger/*=S*/.runtimeType.toString())) {
    injector.map<Logger/*=S*/>(
        (i) => MyLogger/*=S*/(),
       key: Logger/*=S*.runtimeType.toString()
    );
}
```
didn't work for me. My IDE shows error `The getter 'runtimeType' isn't defined for the type 'Logger'`
But the second example is not okay for my needs. What I am trying to do with `injector.map<Logger/*=S*/>` syntax is to tell dependency container that it should resolve any `Logger<T>` as `MyLogger<T>` where T can be any type.
Don't worry about that, I already implemented a work-around which works for me (manually creating instances of logger and resolve it's dependencies from dependency container) so you can close this issue

**Comment by jonsamwell** [comment]
@sxtfv how did you get this working?

**Comment by sxtfv** [comment]
@jonsamwell Nothing complicated. I moved all logic related to Injector into separate class. When I need Logger<T> - I call specific method from that class which instantiates needed logger with it's dependencies. Also, while I register other dependencies - I pass needed logger manually:
```
class DependencyContainer {
  void initialize(Injector injector) {
    injector.map<ClassA>(
        (i) => ClassA(
            logger: MyLogger<ClassA>(
                loggerDependency: i.get<LoggerDependency>(),
            ),
        ),
    );

    //.. same logic for any other class which depends on Logger<T>
  }

  Logger<T> getLogger<T>() => MyLogger<T>(
      loggerDependency: Injector().get<LoggerDependency>(),
  );
}

class LoadingScreen {
  void foo() {
    final logger = DependencyContainer.getLogger<LoadingScreen>();
    ///....
  }
} 
```
