### ISSUE TITLE
getAll with base types possible?

### ISSUE THREAD

**Issue by HerrNiklasRaab** [jonsamwell/flutter_simple_dependency_injection#8]
Hello jonsamwell,

is it possible to implement following behaviour without reflection:

``` dart
UserRepository _userRepository = Injector.getInjector().get<UserRepository>();
ChatRepository _chatRepository = Injector.getInjector().get<ChatRepository>();
PostRepository _postRepository = Injector.getInjector().get<PostRepository>();

var allRepositories = Injector.getInjector().getAll<BaseRepository>();
```

Every Repository is derived from **BaseRepository**.

Would be a nice feature :).

Niklas

**Comment by jonsamwell** [comment]
Hi @HerrNiklasRaab 

I'm not sure this would be possible without the use of mirrors (which can't be used).  The way I can think of getting around this at the moment would be to additionally register each repository as a named instance against the `BaseRepository` type.

```
injector.map<UserRepository>((i) => new UserRepository());
injector.map<BaseRepository>((i) => i.get<UserRepository>(), key: "UserRepository");
injector.map<ChatRepository>((i) => new ChatRepository());
injector.map<BaseRepository>((i) => i.get<ChatRepository>(), key: "ChatRepository");

var allRepositories = Injector.getInjector().getAll<BaseRepository>();
```

This isn't ideal so I'll investigate another solution if I get some free time this week.

**Comment by jonsamwell** [comment]
@HerrNiklasRaab did this help?

**Comment by grAPPfruit** [comment]
This definitely helped me even though I would prefer a prettier solution ;)

**Comment by HerrNiklasRaab** [comment]
I am not using it actively, using it right now.

**Comment by jonsamwell** [comment]
Sorry this is just not possible without the use of mirrors.
