### ISSUE TITLE
[Feature Request] Overriding existing TypeFactory for testing purposes

### ISSUE THREAD

**Issue by rslosarz** [jonsamwell/flutter_simple_dependency_injection#9]
I'd suggest adding a map method for testing purposes, that will allow overriding existing objectKeys. 
This is quite useful while Unit Testing, where tested object uses some Injected implementation that we'd like to mock.

**This is the method I'm thinking of:**

    void mapWithOverride<T>(ObjectFactoryFn<T> factoryFn,
       {bool isSingleton = false, String key}) {
     final objectKey = _makeKey(T, key);
     if (_factories.containsKey(objectKey)) {
       _factories.remove(objectKey); //override instead of throwing exception
     }
     _factories[objectKey] =
     new TypeFactory<T>((i, p) => factoryFn(i), isSingleton);
    }

**This is the case I'm talking about:**
This is tested object:

    class SomeRepository implements RepoInterface {
      final SomeSourceInterface source = Injector.getInjector().get<SomeSourceInterface>();
      @override
      List<Results> getResults() {
        List<Results> list = source.getObjects();
        (...) //some data processing, repo pattern etc.
      }
    }

This is class handling DI initialisation:

    //Class used to 
    class InjectionInit {
      static void init() {
        final injector = Injector.getInjector();
        injector.map<SomeSourceInterface>((i) => new ProdImplementation());
      }
    }

Normally used like this:

    void main() {
      InjectionInit.init();
      runApp(App());
    }

And this is Unit Test class where I'd like to mock SomeSourceInterface:

    import 'package:flutter_simple_dependency_injection/injector.dart';
    import 'package:test_api/test_api.dart';
    import 'package:mockito/mockito.dart';

    class MockImplementation extends Mock implements SomeSourceInterface {}

    void main() {
      group('SomeRepository tests', () {
        SomeRepository repo;
        MockImplementation source;

        setUpAll(() {
          InjectionInit.init();
          source = new MockImplementation();
          final injector = Injector.getInjector();
          injector.mapWithOverride<SomeSourceInterface>((i) => source);
        });

        setUp(() {
          repo = new SomeRepository();
        });

        tearDown(() {
          repo = null;
        });

        test('test', (){
          when(source.getObjects()).thenReturn(...);
          (...)
        });
      });
    }

**Comment by jonsamwell** [comment]
@rslosarz I would just like to understand how you are using the DI.

I would strongly advise that no service or component or anything is dependent on the injector.  I would always ensure a service's dependencies are injected into that service rather than the service knowing about the injector and getting them itself.  This will help to stop the scenario you have just encountered.

As a general rule if you are using the injector outside of initializing it you are doing something wrong.

Therefore, I would ensure the above service looks something like this.

```
class SomeRepository implements RepoInterface {
  final SomeSourceInterface _source;

  SomeRepository(this._source);

  @override
  List<Results> getResults() {
    List<Results> list = _source.getObjects();
    (...) //some data processing, repo pattern etc.
  }
}


class InjectionInit {
  // pass in an injector instance so you are not coupled to static methods
  static void init(Injector injector) {
    injector.map<SomeSourceInterface>((i) => new ProdImplementation());
    injector.map<SomeRepository>((i) => new SomeRepository(i.get<SomeSourceInterface>()));
  }
}

```

Then your test would look like this:

```
import 'package:flutter_simple_dependency_injection/injector.dart';
import 'package:test_api/test_api.dart';
import 'package:mockito/mockito.dart';

class MockImplementation extends Mock implements SomeSourceInterface {}

void main() {
  group('SomeRepository tests', () {
    SomeRepository repo;
    MockImplementation source;

    setUp(() {
      source = new MockImplementation();
      repo = new SomeRepository(source);
    });

    tearDown(() {
      repo = null;
    });

    test('test', (){
      when(source.getObjects()).thenReturn(...);
      (...)
    });
  });
}
```

I hope this help.  Let me know your thoughts.

**Comment by jonsamwell** [comment]
@rslosarz did this approach help?
